sudo: required

services:
  - docker

env:
  - DOCKER_BIND_LOCALHOST=true

language: go

go:
  - 1.5

install:
  - go get golang.org/x/tools/cmd/vet
  - go get github.com/axw/gocov/gocov
  - go get github.com/mattn/goveralls
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/golang/lint/golint
  - go get -t ./...

script:
  # - go vet -x ./...
  - ./coverage --coveralls