go test sudo: required

services:
  - docker

env:
  - DOCKER_BIND_LOCALHOST=true GO15VENDOREXPERIMENT=1

language: go

go:
  - 1.5
  - 1.6

install:
  - go get github.com/axw/gocov/gocov github.com/mattn/goveralls golang.org/x/tools/cmd/cover github.com/pierrre/gotestcover
  # Workaround for travis
  - go get -t -v ./...
  - go install github.com/ory-am/hydra
  - git clone https://github.com/docker-library/official-images.git ~/official-images

script:
  - go test -bench=.* -run=nothing $(go list ./... | grep -v /vendor)
  - go test -race -bench=.* $(go list ./... | grep -v /vendor | grep -v /cmd)
  - gotestcover -coverprofile="cover.out" $(go list ./... | grep -v /vendor/)
  - goveralls -coverprofile="cover.out"
  - docker build -t hydra-travis-ci .
  - docker run -d hydra-travis-ci
  - $GOPATH/bin/hydra host --dangerous-auto-logon &
  - sleep 2
  - $GOPATH/bin/hydra token client --skip-tls-verify