###########################################################################
#######             FOR DEMONSTRATION PURPOSES ONLY                 #######
###########################################################################
#                                                                         #
# If you have not yet read the tutorial, do so now:                       #
#  https://ory-am.gitbooks.io/hydra/content/tutorial.html                 #
#                                                                         #
# This set up is only for demonstration purposes. The login               #
# endpoint can only be used if you follow the steps in the tutorial.      #
#                                                                         #
###########################################################################

version: '2'

services:

  hydra-migrate:
    build:
      context: .
      dockerfile: Dockerfile
    links:
      - postgresd:postgresd
    environment:
#      - LOG_LEVEL=debug
      - DATABASE_URL=postgres://hydra:secret@postgresd:5432/hydra?sslmode=disable
    command:
      migrate sql -e
    restart: on-failure

  hydra:
    build:
      context: .
      dockerfile: Dockerfile
    links:
      - postgresd:postgresd
#     Uncomment the following line to use mysql instead.
#      - mysqld:mysqld
    depends_on:
      - hydra-migrate
    ports:
      # Public port
      - "4444:4444"
      # Admin port
      - "4445:4445"
      # Port for hydra token user
      - "5555:5555"
    command:
      serve all --dangerous-force-http
    environment:
#      - LOG_LEVEL=debug
      - OAUTH2_ISSUER_URL=http://localhost:4444
      - OAUTH2_CONSENT_URL=http://localhost:3000/consent
      - OAUTH2_LOGIN_URL=http://localhost:3000/login
      - DATABASE_URL=postgres://hydra:secret@postgresd:5432/hydra?sslmode=disable
#     Uncomment the following line to use mysql instead.
#      - DATABASE_URL=mysql://root:secret@tcp(mysqld:3306)/mysql?parseTime=true
      - SYSTEM_SECRET=youReallyNeedToChangeThis
      - OAUTH2_SHARE_ERROR_DEBUG=1
      - OIDC_SUBJECT_TYPES_SUPPORTED=public,pairwise
      - OIDC_SUBJECT_TYPE_PAIRWISE_SALT=youReallyNeedToChangeThis
#     - OAUTH2_ACCESS_TOKEN_STRATEGY=jwt
    restart: unless-stopped

  consent:
    environment:
      - HYDRA_ADMIN_URL=http://hydra:4445
    image: oryd/hydra-login-consent-node:v1.0.0-beta.9
    links:
      - hydra
    ports:
      - "3000:3000"
    restart: unless-stopped

  postgresd:
    image: postgres:9.6
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=hydra
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=hydra

#  Uncomment the following section to use mysql instead.
#  mysqld:
#    image: mysql:5.7
#    environment:
#      - MYSQL_ROOT_PASSWORD=secret
