###########################################################################
#######             FOR DEMONSTRATION PURPOSES ONLY                 #######
###########################################################################
#                                                                         #
# If you have not yet read the tutorial, do so now:                       #
#  https://ory-am.gitbooks.io/hydra/content/tutorial.html                 #
#                                                                         #
# This set up is only for demonstration purposes. The login               #
# endpoint can only be used if you follow the steps in the tutorial.      #
#                                                                         #
###########################################################################

version: '2'

services:

  hydra-migrate:
    build:
      context: .
      dockerfile: Dockerfile-alpine
    links:
      - postgresd:postgresd
    command:
      migrate sql postgres://hydra:secret@postgresd:5432/hydra?sslmode=disable
    restart: on-failure

  hydra:
    build:
      context: .
      dockerfile: Dockerfile-alpine
    links:
      - postgresd:postgresd
#     Uncomment the following line to use mysql instead.
#      - mysqld:mysqld
    depends_on:
      - hydra-migrate
    volumes:
      - hydravolume:/root
    ports:
      - "4444:4444"
      - "4445:4445"
    command:
      host --dangerous-auto-logon --dangerous-force-http --disable-telemetry
    environment:
      - LOG_LEVEL=debug
      - ISSUER=http://localhost:4444
      - CONSENT_URL=http://localhost:3000/consent
      - DATABASE_URL=postgres://hydra:secret@postgresd:5432/hydra?sslmode=disable
#     Uncomment the following line to use mysql instead.
#      - DATABASE_URL=mysql://root:secret@tcp(mysqld:3306)/mysql?parseTime=true
      - FORCE_ROOT_CLIENT_CREDENTIALS=admin:demo-password
      - SYSTEM_SECRET=youReallyNeedToChangeThis
    restart: unless-stopped

  consent:
    environment:
      - HYDRA_URL=http://hydra:4444
      - HYDRA_CLIENT_ID=admin
      - HYDRA_CLIENT_SECRET=demo-password
      - NODE_TLS_REJECT_UNAUTHORIZED=0
    image: oryd/hydra-consent-app-express:v0.10.0-alpha.7
    links:
      - hydra
    ports:
      - "3000:3000"
    restart: unless-stopped

  postgresd:
    image: postgres:9.6
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=hydra
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=hydra

#  Uncomment the following section to use mysql instead.
#  mysqld:
#    image: mysql:5.7
#    environment:
#      - MYSQL_ROOT_PASSWORD=secret

volumes:
  hydravolume:
    driver: local
