[[constraint]]
  name = "github.com/dgrijalva/jwt-go"
  version = "3.0.0"

[[constraint]]
  name = "github.com/go-sql-driver/mysql"
  version = "1.3.0"

[[constraint]]
  name = "github.com/gorilla/context"
  version = "1.1.0"

[[constraint]]
  name = "github.com/gorilla/sessions"
  version = "1.1.0"

[[constraint]]
  name = "github.com/imdario/mergo"
  version = "0.2.2"

[[constraint]]
  name = "github.com/julienschmidt/httprouter"
  version = "1.1.0"

[[constraint]]
  name = "github.com/oleiade/reflections"
  version = "1.0.0"

[[constraint]]
  name = "github.com/ory/fosite"
  version = "0.10.0"

[[constraint]]
  name = "github.com/ory/graceful"
  version = "0.1.0"

[[constraint]]
  name = "github.com/ory/herodot"
  version = "0.1.1"

[[constraint]]
  name = "github.com/ory/ladon"
  version = "0.8.2"

[[constraint]]
  name = "github.com/pborman/uuid"
  version = "1.0.0"

[[constraint]]
  name = "github.com/pkg/errors"
  version = "0.8.0"

[[constraint]]
  name = "github.com/pkg/profile"
  version = "1.2.1"

[[constraint]]
  name = "github.com/square/go-jose"
  version = "2.1.3"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.1.4"

[[constraint]]
  name = "github.com/toqueteos/webbrowser"
  version = "1.0.0"

[[constraint]]
  name = "github.com/urfave/negroni"
  version = "0.2.0"
