language: go
go:
  - 1.4
  - 1.3
  - 1.2
install:
  - go get github.com/elazarl/goproxy
  - go get golang.org/x/net/publicsuffix
notifications:
  email:
    recipients: parnurzeal@gmail.com
    on_success: change
    on_failure: always
