name: Generate and Publish Milestone Document

on:
  workflow_dispatch:
  issues:
    types: [opened, closed, edited, demilestoned, milestoned, reopened, assigned, unassigned, labeled, unlabeled]
  pull_request:
    types: [opened, closed, edited, demilestoned, milestoned, reopened, assigned, unassigned, labeled, unlabeled]

jobs:
  milestone:
    name: Generate and Publish Milestone Document
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Milestone Documentation Generator
        uses: ory/milestone-action@v0.0.10
        with:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          outputFile: docs/docs/milestones.md
      - name: Commit Milestone Documentation
        uses: EndBug/add-and-commit@v4.4.0
        with:
          message: "autogen(docs): update milestone"
          author_name: aeneasr
          author_email: "3372410+aeneasr@users.noreply.github.com"
